              ## storySystem by hofwq. ##
## Unauthorized copying, distribution, or use is prohibited. ##

## berriesLoc - Location from which quest will begin.
## berriesLocRadius - Trigger range.
## borderFirst/borderSecond - Total area on which player can move, requires two coordinates, works like a square.
## boat_1/2/3/4 - Place where boats will spawn.

NPC_Olga:
  ID: 0
berriesLoc:
  x: 0
  y: 0
  z: 0
berriesLocRadius:
  blocks: 0
borderFirst:
  x: 0
  y: 0
  z: 0
borderSecond:
  x: 0
  y: 0
  z: 0
boat_1:
  x: 0
  z: 0
boat_2:
  x: 0
  z: 0
boat_3:
  x: 0
  z: 0
boat_4:
  x: 0
  z: 0