name: StorySystem
version: '1.6-beta(rev. 1)'
main: ru.hofwq.storySystem.StorySystem
api-version: '1.21'
authors: [ hofwq ]
website: play.esmcrp.ru

commands:
  setstoryflag:
    aliases:
      - setstfl
    description: Set Story flag to player (Only for debugging).
    usage: /setstoryflag [player] [flag]
  resetstoryflag:
    aliases:
      - resetstfl
    description: Reset Player Story flag.
    usage: /resetstoryflag [player] [flag]
  basketclick:
    usage: /basketclick <name>
  packclick:
    usage: /packclick <name>
  fridgeclick:
    usage: /fridgeclick <name>